// GENERATED by tools/gen_osd_tables.py - do not edit by hand.
//
// On-screen keyboard tables, as combinational logic (no block RAM is
// free). See osd_keyboard.sv.
`default_nettype none

// 63 glyphs, 5x7 in an 8x8 cell: bits[4:0] = pixel columns 1..5
// (bit 4 leftmost). Rows 7 are blank.
module osd_font_rom (
    input  wire [5:0] ch,
    input  wire [2:0] row,
    output reg  [4:0] bits
);
    always_comb begin
        case ({ch, row})
            {6'd1, 3'd0}: bits = 5'b01110; // '0'
            {6'd1, 3'd1}: bits = 5'b10001; // '0'
            {6'd1, 3'd2}: bits = 5'b10011; // '0'
            {6'd1, 3'd3}: bits = 5'b10101; // '0'
            {6'd1, 3'd4}: bits = 5'b11001; // '0'
            {6'd1, 3'd5}: bits = 5'b10001; // '0'
            {6'd1, 3'd6}: bits = 5'b01110; // '0'
            {6'd2, 3'd0}: bits = 5'b00100; // '1'
            {6'd2, 3'd1}: bits = 5'b01100; // '1'
            {6'd2, 3'd2}: bits = 5'b00100; // '1'
            {6'd2, 3'd3}: bits = 5'b00100; // '1'
            {6'd2, 3'd4}: bits = 5'b00100; // '1'
            {6'd2, 3'd5}: bits = 5'b00100; // '1'
            {6'd2, 3'd6}: bits = 5'b01110; // '1'
            {6'd3, 3'd0}: bits = 5'b01110; // '2'
            {6'd3, 3'd1}: bits = 5'b10001; // '2'
            {6'd3, 3'd2}: bits = 5'b00001; // '2'
            {6'd3, 3'd3}: bits = 5'b00110; // '2'
            {6'd3, 3'd4}: bits = 5'b01000; // '2'
            {6'd3, 3'd5}: bits = 5'b10000; // '2'
            {6'd3, 3'd6}: bits = 5'b11111; // '2'
            {6'd4, 3'd0}: bits = 5'b01110; // '3'
            {6'd4, 3'd1}: bits = 5'b10001; // '3'
            {6'd4, 3'd2}: bits = 5'b00001; // '3'
            {6'd4, 3'd3}: bits = 5'b00110; // '3'
            {6'd4, 3'd4}: bits = 5'b00001; // '3'
            {6'd4, 3'd5}: bits = 5'b10001; // '3'
            {6'd4, 3'd6}: bits = 5'b01110; // '3'
            {6'd5, 3'd0}: bits = 5'b00010; // '4'
            {6'd5, 3'd1}: bits = 5'b00110; // '4'
            {6'd5, 3'd2}: bits = 5'b01010; // '4'
            {6'd5, 3'd3}: bits = 5'b10010; // '4'
            {6'd5, 3'd4}: bits = 5'b11111; // '4'
            {6'd5, 3'd5}: bits = 5'b00010; // '4'
            {6'd5, 3'd6}: bits = 5'b00010; // '4'
            {6'd6, 3'd0}: bits = 5'b11111; // '5'
            {6'd6, 3'd1}: bits = 5'b10000; // '5'
            {6'd6, 3'd2}: bits = 5'b11110; // '5'
            {6'd6, 3'd3}: bits = 5'b00001; // '5'
            {6'd6, 3'd4}: bits = 5'b00001; // '5'
            {6'd6, 3'd5}: bits = 5'b10001; // '5'
            {6'd6, 3'd6}: bits = 5'b01110; // '5'
            {6'd7, 3'd0}: bits = 5'b00110; // '6'
            {6'd7, 3'd1}: bits = 5'b01000; // '6'
            {6'd7, 3'd2}: bits = 5'b10000; // '6'
            {6'd7, 3'd3}: bits = 5'b11110; // '6'
            {6'd7, 3'd4}: bits = 5'b10001; // '6'
            {6'd7, 3'd5}: bits = 5'b10001; // '6'
            {6'd7, 3'd6}: bits = 5'b01110; // '6'
            {6'd8, 3'd0}: bits = 5'b11111; // '7'
            {6'd8, 3'd1}: bits = 5'b00001; // '7'
            {6'd8, 3'd2}: bits = 5'b00010; // '7'
            {6'd8, 3'd3}: bits = 5'b00100; // '7'
            {6'd8, 3'd4}: bits = 5'b01000; // '7'
            {6'd8, 3'd5}: bits = 5'b01000; // '7'
            {6'd8, 3'd6}: bits = 5'b01000; // '7'
            {6'd9, 3'd0}: bits = 5'b01110; // '8'
            {6'd9, 3'd1}: bits = 5'b10001; // '8'
            {6'd9, 3'd2}: bits = 5'b10001; // '8'
            {6'd9, 3'd3}: bits = 5'b01110; // '8'
            {6'd9, 3'd4}: bits = 5'b10001; // '8'
            {6'd9, 3'd5}: bits = 5'b10001; // '8'
            {6'd9, 3'd6}: bits = 5'b01110; // '8'
            {6'd10, 3'd0}: bits = 5'b01110; // '9'
            {6'd10, 3'd1}: bits = 5'b10001; // '9'
            {6'd10, 3'd2}: bits = 5'b10001; // '9'
            {6'd10, 3'd3}: bits = 5'b01111; // '9'
            {6'd10, 3'd4}: bits = 5'b00001; // '9'
            {6'd10, 3'd5}: bits = 5'b00010; // '9'
            {6'd10, 3'd6}: bits = 5'b01100; // '9'
            {6'd11, 3'd0}: bits = 5'b01110; // 'A'
            {6'd11, 3'd1}: bits = 5'b10001; // 'A'
            {6'd11, 3'd2}: bits = 5'b10001; // 'A'
            {6'd11, 3'd3}: bits = 5'b11111; // 'A'
            {6'd11, 3'd4}: bits = 5'b10001; // 'A'
            {6'd11, 3'd5}: bits = 5'b10001; // 'A'
            {6'd11, 3'd6}: bits = 5'b10001; // 'A'
            {6'd12, 3'd0}: bits = 5'b11110; // 'B'
            {6'd12, 3'd1}: bits = 5'b10001; // 'B'
            {6'd12, 3'd2}: bits = 5'b10001; // 'B'
            {6'd12, 3'd3}: bits = 5'b11110; // 'B'
            {6'd12, 3'd4}: bits = 5'b10001; // 'B'
            {6'd12, 3'd5}: bits = 5'b10001; // 'B'
            {6'd12, 3'd6}: bits = 5'b11110; // 'B'
            {6'd13, 3'd0}: bits = 5'b01110; // 'C'
            {6'd13, 3'd1}: bits = 5'b10001; // 'C'
            {6'd13, 3'd2}: bits = 5'b10000; // 'C'
            {6'd13, 3'd3}: bits = 5'b10000; // 'C'
            {6'd13, 3'd4}: bits = 5'b10000; // 'C'
            {6'd13, 3'd5}: bits = 5'b10001; // 'C'
            {6'd13, 3'd6}: bits = 5'b01110; // 'C'
            {6'd14, 3'd0}: bits = 5'b11110; // 'D'
            {6'd14, 3'd1}: bits = 5'b10001; // 'D'
            {6'd14, 3'd2}: bits = 5'b10001; // 'D'
            {6'd14, 3'd3}: bits = 5'b10001; // 'D'
            {6'd14, 3'd4}: bits = 5'b10001; // 'D'
            {6'd14, 3'd5}: bits = 5'b10001; // 'D'
            {6'd14, 3'd6}: bits = 5'b11110; // 'D'
            {6'd15, 3'd0}: bits = 5'b11111; // 'E'
            {6'd15, 3'd1}: bits = 5'b10000; // 'E'
            {6'd15, 3'd2}: bits = 5'b10000; // 'E'
            {6'd15, 3'd3}: bits = 5'b11110; // 'E'
            {6'd15, 3'd4}: bits = 5'b10000; // 'E'
            {6'd15, 3'd5}: bits = 5'b10000; // 'E'
            {6'd15, 3'd6}: bits = 5'b11111; // 'E'
            {6'd16, 3'd0}: bits = 5'b11111; // 'F'
            {6'd16, 3'd1}: bits = 5'b10000; // 'F'
            {6'd16, 3'd2}: bits = 5'b10000; // 'F'
            {6'd16, 3'd3}: bits = 5'b11110; // 'F'
            {6'd16, 3'd4}: bits = 5'b10000; // 'F'
            {6'd16, 3'd5}: bits = 5'b10000; // 'F'
            {6'd16, 3'd6}: bits = 5'b10000; // 'F'
            {6'd17, 3'd0}: bits = 5'b01110; // 'G'
            {6'd17, 3'd1}: bits = 5'b10001; // 'G'
            {6'd17, 3'd2}: bits = 5'b10000; // 'G'
            {6'd17, 3'd3}: bits = 5'b10111; // 'G'
            {6'd17, 3'd4}: bits = 5'b10001; // 'G'
            {6'd17, 3'd5}: bits = 5'b10001; // 'G'
            {6'd17, 3'd6}: bits = 5'b01111; // 'G'
            {6'd18, 3'd0}: bits = 5'b10001; // 'H'
            {6'd18, 3'd1}: bits = 5'b10001; // 'H'
            {6'd18, 3'd2}: bits = 5'b10001; // 'H'
            {6'd18, 3'd3}: bits = 5'b11111; // 'H'
            {6'd18, 3'd4}: bits = 5'b10001; // 'H'
            {6'd18, 3'd5}: bits = 5'b10001; // 'H'
            {6'd18, 3'd6}: bits = 5'b10001; // 'H'
            {6'd19, 3'd0}: bits = 5'b01110; // 'I'
            {6'd19, 3'd1}: bits = 5'b00100; // 'I'
            {6'd19, 3'd2}: bits = 5'b00100; // 'I'
            {6'd19, 3'd3}: bits = 5'b00100; // 'I'
            {6'd19, 3'd4}: bits = 5'b00100; // 'I'
            {6'd19, 3'd5}: bits = 5'b00100; // 'I'
            {6'd19, 3'd6}: bits = 5'b01110; // 'I'
            {6'd20, 3'd0}: bits = 5'b00111; // 'J'
            {6'd20, 3'd1}: bits = 5'b00010; // 'J'
            {6'd20, 3'd2}: bits = 5'b00010; // 'J'
            {6'd20, 3'd3}: bits = 5'b00010; // 'J'
            {6'd20, 3'd4}: bits = 5'b00010; // 'J'
            {6'd20, 3'd5}: bits = 5'b10010; // 'J'
            {6'd20, 3'd6}: bits = 5'b01100; // 'J'
            {6'd21, 3'd0}: bits = 5'b10001; // 'K'
            {6'd21, 3'd1}: bits = 5'b10010; // 'K'
            {6'd21, 3'd2}: bits = 5'b10100; // 'K'
            {6'd21, 3'd3}: bits = 5'b11000; // 'K'
            {6'd21, 3'd4}: bits = 5'b10100; // 'K'
            {6'd21, 3'd5}: bits = 5'b10010; // 'K'
            {6'd21, 3'd6}: bits = 5'b10001; // 'K'
            {6'd22, 3'd0}: bits = 5'b10000; // 'L'
            {6'd22, 3'd1}: bits = 5'b10000; // 'L'
            {6'd22, 3'd2}: bits = 5'b10000; // 'L'
            {6'd22, 3'd3}: bits = 5'b10000; // 'L'
            {6'd22, 3'd4}: bits = 5'b10000; // 'L'
            {6'd22, 3'd5}: bits = 5'b10000; // 'L'
            {6'd22, 3'd6}: bits = 5'b11111; // 'L'
            {6'd23, 3'd0}: bits = 5'b10001; // 'M'
            {6'd23, 3'd1}: bits = 5'b11011; // 'M'
            {6'd23, 3'd2}: bits = 5'b10101; // 'M'
            {6'd23, 3'd3}: bits = 5'b10101; // 'M'
            {6'd23, 3'd4}: bits = 5'b10001; // 'M'
            {6'd23, 3'd5}: bits = 5'b10001; // 'M'
            {6'd23, 3'd6}: bits = 5'b10001; // 'M'
            {6'd24, 3'd0}: bits = 5'b10001; // 'N'
            {6'd24, 3'd1}: bits = 5'b10001; // 'N'
            {6'd24, 3'd2}: bits = 5'b11001; // 'N'
            {6'd24, 3'd3}: bits = 5'b10101; // 'N'
            {6'd24, 3'd4}: bits = 5'b10011; // 'N'
            {6'd24, 3'd5}: bits = 5'b10001; // 'N'
            {6'd24, 3'd6}: bits = 5'b10001; // 'N'
            {6'd25, 3'd0}: bits = 5'b01110; // 'O'
            {6'd25, 3'd1}: bits = 5'b10001; // 'O'
            {6'd25, 3'd2}: bits = 5'b10001; // 'O'
            {6'd25, 3'd3}: bits = 5'b10001; // 'O'
            {6'd25, 3'd4}: bits = 5'b10001; // 'O'
            {6'd25, 3'd5}: bits = 5'b10001; // 'O'
            {6'd25, 3'd6}: bits = 5'b01110; // 'O'
            {6'd26, 3'd0}: bits = 5'b11110; // 'P'
            {6'd26, 3'd1}: bits = 5'b10001; // 'P'
            {6'd26, 3'd2}: bits = 5'b10001; // 'P'
            {6'd26, 3'd3}: bits = 5'b11110; // 'P'
            {6'd26, 3'd4}: bits = 5'b10000; // 'P'
            {6'd26, 3'd5}: bits = 5'b10000; // 'P'
            {6'd26, 3'd6}: bits = 5'b10000; // 'P'
            {6'd27, 3'd0}: bits = 5'b01110; // 'Q'
            {6'd27, 3'd1}: bits = 5'b10001; // 'Q'
            {6'd27, 3'd2}: bits = 5'b10001; // 'Q'
            {6'd27, 3'd3}: bits = 5'b10001; // 'Q'
            {6'd27, 3'd4}: bits = 5'b10101; // 'Q'
            {6'd27, 3'd5}: bits = 5'b10010; // 'Q'
            {6'd27, 3'd6}: bits = 5'b01101; // 'Q'
            {6'd28, 3'd0}: bits = 5'b11110; // 'R'
            {6'd28, 3'd1}: bits = 5'b10001; // 'R'
            {6'd28, 3'd2}: bits = 5'b10001; // 'R'
            {6'd28, 3'd3}: bits = 5'b11110; // 'R'
            {6'd28, 3'd4}: bits = 5'b10100; // 'R'
            {6'd28, 3'd5}: bits = 5'b10010; // 'R'
            {6'd28, 3'd6}: bits = 5'b10001; // 'R'
            {6'd29, 3'd0}: bits = 5'b01111; // 'S'
            {6'd29, 3'd1}: bits = 5'b10000; // 'S'
            {6'd29, 3'd2}: bits = 5'b10000; // 'S'
            {6'd29, 3'd3}: bits = 5'b01110; // 'S'
            {6'd29, 3'd4}: bits = 5'b00001; // 'S'
            {6'd29, 3'd5}: bits = 5'b00001; // 'S'
            {6'd29, 3'd6}: bits = 5'b11110; // 'S'
            {6'd30, 3'd0}: bits = 5'b11111; // 'T'
            {6'd30, 3'd1}: bits = 5'b00100; // 'T'
            {6'd30, 3'd2}: bits = 5'b00100; // 'T'
            {6'd30, 3'd3}: bits = 5'b00100; // 'T'
            {6'd30, 3'd4}: bits = 5'b00100; // 'T'
            {6'd30, 3'd5}: bits = 5'b00100; // 'T'
            {6'd30, 3'd6}: bits = 5'b00100; // 'T'
            {6'd31, 3'd0}: bits = 5'b10001; // 'U'
            {6'd31, 3'd1}: bits = 5'b10001; // 'U'
            {6'd31, 3'd2}: bits = 5'b10001; // 'U'
            {6'd31, 3'd3}: bits = 5'b10001; // 'U'
            {6'd31, 3'd4}: bits = 5'b10001; // 'U'
            {6'd31, 3'd5}: bits = 5'b10001; // 'U'
            {6'd31, 3'd6}: bits = 5'b01110; // 'U'
            {6'd32, 3'd0}: bits = 5'b10001; // 'V'
            {6'd32, 3'd1}: bits = 5'b10001; // 'V'
            {6'd32, 3'd2}: bits = 5'b10001; // 'V'
            {6'd32, 3'd3}: bits = 5'b10001; // 'V'
            {6'd32, 3'd4}: bits = 5'b10001; // 'V'
            {6'd32, 3'd5}: bits = 5'b01010; // 'V'
            {6'd32, 3'd6}: bits = 5'b00100; // 'V'
            {6'd33, 3'd0}: bits = 5'b10001; // 'W'
            {6'd33, 3'd1}: bits = 5'b10001; // 'W'
            {6'd33, 3'd2}: bits = 5'b10001; // 'W'
            {6'd33, 3'd3}: bits = 5'b10101; // 'W'
            {6'd33, 3'd4}: bits = 5'b10101; // 'W'
            {6'd33, 3'd5}: bits = 5'b10101; // 'W'
            {6'd33, 3'd6}: bits = 5'b01010; // 'W'
            {6'd34, 3'd0}: bits = 5'b10001; // 'X'
            {6'd34, 3'd1}: bits = 5'b10001; // 'X'
            {6'd34, 3'd2}: bits = 5'b01010; // 'X'
            {6'd34, 3'd3}: bits = 5'b00100; // 'X'
            {6'd34, 3'd4}: bits = 5'b01010; // 'X'
            {6'd34, 3'd5}: bits = 5'b10001; // 'X'
            {6'd34, 3'd6}: bits = 5'b10001; // 'X'
            {6'd35, 3'd0}: bits = 5'b10001; // 'Y'
            {6'd35, 3'd1}: bits = 5'b10001; // 'Y'
            {6'd35, 3'd2}: bits = 5'b01010; // 'Y'
            {6'd35, 3'd3}: bits = 5'b00100; // 'Y'
            {6'd35, 3'd4}: bits = 5'b00100; // 'Y'
            {6'd35, 3'd5}: bits = 5'b00100; // 'Y'
            {6'd35, 3'd6}: bits = 5'b00100; // 'Y'
            {6'd36, 3'd0}: bits = 5'b11111; // 'Z'
            {6'd36, 3'd1}: bits = 5'b00001; // 'Z'
            {6'd36, 3'd2}: bits = 5'b00010; // 'Z'
            {6'd36, 3'd3}: bits = 5'b00100; // 'Z'
            {6'd36, 3'd4}: bits = 5'b01000; // 'Z'
            {6'd36, 3'd5}: bits = 5'b10000; // 'Z'
            {6'd36, 3'd6}: bits = 5'b11111; // 'Z'
            {6'd37, 3'd1}: bits = 5'b01100; // ':'
            {6'd37, 3'd2}: bits = 5'b01100; // ':'
            {6'd37, 3'd4}: bits = 5'b01100; // ':'
            {6'd37, 3'd5}: bits = 5'b01100; // ':'
            {6'd38, 3'd3}: bits = 5'b11111; // '-'
            {6'd39, 3'd0}: bits = 5'b01110; // '@'
            {6'd39, 3'd1}: bits = 5'b10001; // '@'
            {6'd39, 3'd2}: bits = 5'b10111; // '@'
            {6'd39, 3'd3}: bits = 5'b10101; // '@'
            {6'd39, 3'd4}: bits = 5'b10111; // '@'
            {6'd39, 3'd5}: bits = 5'b10000; // '@'
            {6'd39, 3'd6}: bits = 5'b01111; // '@'
            {6'd40, 3'd1}: bits = 5'b01100; // ';'
            {6'd40, 3'd2}: bits = 5'b01100; // ';'
            {6'd40, 3'd4}: bits = 5'b01100; // ';'
            {6'd40, 3'd5}: bits = 5'b00100; // ';'
            {6'd40, 3'd6}: bits = 5'b01000; // ';'
            {6'd41, 3'd4}: bits = 5'b01100; // ','
            {6'd41, 3'd5}: bits = 5'b00100; // ','
            {6'd41, 3'd6}: bits = 5'b01000; // ','
            {6'd42, 3'd5}: bits = 5'b01100; // '.'
            {6'd42, 3'd6}: bits = 5'b01100; // '.'
            {6'd43, 3'd1}: bits = 5'b00001; // '/'
            {6'd43, 3'd2}: bits = 5'b00010; // '/'
            {6'd43, 3'd3}: bits = 5'b00100; // '/'
            {6'd43, 3'd4}: bits = 5'b01000; // '/'
            {6'd43, 3'd5}: bits = 5'b10000; // '/'
            {6'd44, 3'd0}: bits = 5'b00100; // 'UP'
            {6'd44, 3'd1}: bits = 5'b01110; // 'UP'
            {6'd44, 3'd2}: bits = 5'b10101; // 'UP'
            {6'd44, 3'd3}: bits = 5'b00100; // 'UP'
            {6'd44, 3'd4}: bits = 5'b00100; // 'UP'
            {6'd44, 3'd5}: bits = 5'b00100; // 'UP'
            {6'd44, 3'd6}: bits = 5'b00100; // 'UP'
            {6'd45, 3'd0}: bits = 5'b00100; // 'DN'
            {6'd45, 3'd1}: bits = 5'b00100; // 'DN'
            {6'd45, 3'd2}: bits = 5'b00100; // 'DN'
            {6'd45, 3'd3}: bits = 5'b00100; // 'DN'
            {6'd45, 3'd4}: bits = 5'b10101; // 'DN'
            {6'd45, 3'd5}: bits = 5'b01110; // 'DN'
            {6'd45, 3'd6}: bits = 5'b00100; // 'DN'
            {6'd46, 3'd1}: bits = 5'b00100; // 'LT'
            {6'd46, 3'd2}: bits = 5'b01000; // 'LT'
            {6'd46, 3'd3}: bits = 5'b11111; // 'LT'
            {6'd46, 3'd4}: bits = 5'b01000; // 'LT'
            {6'd46, 3'd5}: bits = 5'b00100; // 'LT'
            {6'd47, 3'd1}: bits = 5'b00100; // 'RT'
            {6'd47, 3'd2}: bits = 5'b00010; // 'RT'
            {6'd47, 3'd3}: bits = 5'b11111; // 'RT'
            {6'd47, 3'd4}: bits = 5'b00010; // 'RT'
            {6'd47, 3'd5}: bits = 5'b00100; // 'RT'
            {6'd48, 3'd0}: bits = 5'b00100; // '!'
            {6'd48, 3'd1}: bits = 5'b00100; // '!'
            {6'd48, 3'd2}: bits = 5'b00100; // '!'
            {6'd48, 3'd3}: bits = 5'b00100; // '!'
            {6'd48, 3'd4}: bits = 5'b00100; // '!'
            {6'd48, 3'd6}: bits = 5'b00100; // '!'
            {6'd49, 3'd0}: bits = 5'b01010; // '"'
            {6'd49, 3'd1}: bits = 5'b01010; // '"'
            {6'd49, 3'd2}: bits = 5'b01010; // '"'
            {6'd50, 3'd0}: bits = 5'b01010; // '#'
            {6'd50, 3'd1}: bits = 5'b01010; // '#'
            {6'd50, 3'd2}: bits = 5'b11111; // '#'
            {6'd50, 3'd3}: bits = 5'b01010; // '#'
            {6'd50, 3'd4}: bits = 5'b11111; // '#'
            {6'd50, 3'd5}: bits = 5'b01010; // '#'
            {6'd50, 3'd6}: bits = 5'b01010; // '#'
            {6'd51, 3'd0}: bits = 5'b00100; // '$'
            {6'd51, 3'd1}: bits = 5'b01111; // '$'
            {6'd51, 3'd2}: bits = 5'b10100; // '$'
            {6'd51, 3'd3}: bits = 5'b01110; // '$'
            {6'd51, 3'd4}: bits = 5'b00101; // '$'
            {6'd51, 3'd5}: bits = 5'b11110; // '$'
            {6'd51, 3'd6}: bits = 5'b00100; // '$'
            {6'd52, 3'd0}: bits = 5'b11000; // '%'
            {6'd52, 3'd1}: bits = 5'b11001; // '%'
            {6'd52, 3'd2}: bits = 5'b00010; // '%'
            {6'd52, 3'd3}: bits = 5'b00100; // '%'
            {6'd52, 3'd4}: bits = 5'b01000; // '%'
            {6'd52, 3'd5}: bits = 5'b10011; // '%'
            {6'd52, 3'd6}: bits = 5'b00011; // '%'
            {6'd53, 3'd0}: bits = 5'b01100; // '&'
            {6'd53, 3'd1}: bits = 5'b10010; // '&'
            {6'd53, 3'd2}: bits = 5'b10100; // '&'
            {6'd53, 3'd3}: bits = 5'b01000; // '&'
            {6'd53, 3'd4}: bits = 5'b10101; // '&'
            {6'd53, 3'd5}: bits = 5'b10010; // '&'
            {6'd53, 3'd6}: bits = 5'b01101; // '&'
            {6'd54, 3'd0}: bits = 5'b00100; // "'"
            {6'd54, 3'd1}: bits = 5'b00100; // "'"
            {6'd54, 3'd2}: bits = 5'b01000; // "'"
            {6'd55, 3'd0}: bits = 5'b00010; // '('
            {6'd55, 3'd1}: bits = 5'b00100; // '('
            {6'd55, 3'd2}: bits = 5'b01000; // '('
            {6'd55, 3'd3}: bits = 5'b01000; // '('
            {6'd55, 3'd4}: bits = 5'b01000; // '('
            {6'd55, 3'd5}: bits = 5'b00100; // '('
            {6'd55, 3'd6}: bits = 5'b00010; // '('
            {6'd56, 3'd0}: bits = 5'b01000; // ')'
            {6'd56, 3'd1}: bits = 5'b00100; // ')'
            {6'd56, 3'd2}: bits = 5'b00010; // ')'
            {6'd56, 3'd3}: bits = 5'b00010; // ')'
            {6'd56, 3'd4}: bits = 5'b00010; // ')'
            {6'd56, 3'd5}: bits = 5'b00100; // ')'
            {6'd56, 3'd6}: bits = 5'b01000; // ')'
            {6'd57, 3'd1}: bits = 5'b00100; // '*'
            {6'd57, 3'd2}: bits = 5'b10101; // '*'
            {6'd57, 3'd3}: bits = 5'b01110; // '*'
            {6'd57, 3'd4}: bits = 5'b10101; // '*'
            {6'd57, 3'd5}: bits = 5'b00100; // '*'
            {6'd58, 3'd2}: bits = 5'b11111; // '='
            {6'd58, 3'd4}: bits = 5'b11111; // '='
            {6'd59, 3'd1}: bits = 5'b00100; // '+'
            {6'd59, 3'd2}: bits = 5'b00100; // '+'
            {6'd59, 3'd3}: bits = 5'b11111; // '+'
            {6'd59, 3'd4}: bits = 5'b00100; // '+'
            {6'd59, 3'd5}: bits = 5'b00100; // '+'
            {6'd60, 3'd0}: bits = 5'b00010; // '<'
            {6'd60, 3'd1}: bits = 5'b00100; // '<'
            {6'd60, 3'd2}: bits = 5'b01000; // '<'
            {6'd60, 3'd3}: bits = 5'b10000; // '<'
            {6'd60, 3'd4}: bits = 5'b01000; // '<'
            {6'd60, 3'd5}: bits = 5'b00100; // '<'
            {6'd60, 3'd6}: bits = 5'b00010; // '<'
            {6'd61, 3'd0}: bits = 5'b01000; // '>'
            {6'd61, 3'd1}: bits = 5'b00100; // '>'
            {6'd61, 3'd2}: bits = 5'b00010; // '>'
            {6'd61, 3'd3}: bits = 5'b00001; // '>'
            {6'd61, 3'd4}: bits = 5'b00010; // '>'
            {6'd61, 3'd5}: bits = 5'b00100; // '>'
            {6'd61, 3'd6}: bits = 5'b01000; // '>'
            {6'd62, 3'd0}: bits = 5'b01110; // '?'
            {6'd62, 3'd1}: bits = 5'b10001; // '?'
            {6'd62, 3'd2}: bits = 5'b00001; // '?'
            {6'd62, 3'd3}: bits = 5'b00010; // '?'
            {6'd62, 3'd4}: bits = 5'b00100; // '?'
            {6'd62, 3'd6}: bits = 5'b00100; // '?'
            default: bits = 5'b00000;
        endcase
    end
endmodule

// Key attributes by key id (0..52).
//   start/width - in 8-pixel half-units across the 256-pixel panel
//   nchars, c0..c4 - label; sh - shifted label (1 char), has_sh valid
//   mrow/mcol - Dragon matrix position; is_shift - SHIFT latch key
//   prow - panel row (0..4) the key sits on
module osd_key_table (
    input  wire [5:0] id,
    output reg  [4:0] start,
    output reg  [4:0] width,
    output reg  [2:0] nchars,
    output reg  [5:0] c0, c1, c2, c3, c4,
    output reg  [5:0] sh,
    output reg        has_sh,
    output reg  [2:0] mrow,
    output reg  [2:0] mcol,
    output reg        is_shift,
    output reg  [2:0] prow
);
    always_comb begin
        start = 5'd0; width = 5'd0; nchars = 3'd0;
        c0 = 6'd0; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0;
        sh = 6'd0; has_sh = 1'b0; mrow = 3'd0; mcol = 3'd0; is_shift = 1'b0; prow = 3'd0;
        case (id)
            6'd0: begin start = 5'd2; width = 5'd2; nchars = 3'd1; c0 = 6'd2; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd48; has_sh = 1'b1; mrow = 3'd0; mcol = 3'd1; is_shift = 1'b0; prow = 3'd0; end // 1
            6'd1: begin start = 5'd4; width = 5'd2; nchars = 3'd1; c0 = 6'd3; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd49; has_sh = 1'b1; mrow = 3'd0; mcol = 3'd2; is_shift = 1'b0; prow = 3'd0; end // 2
            6'd2: begin start = 5'd6; width = 5'd2; nchars = 3'd1; c0 = 6'd4; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd50; has_sh = 1'b1; mrow = 3'd0; mcol = 3'd3; is_shift = 1'b0; prow = 3'd0; end // 3
            6'd3: begin start = 5'd8; width = 5'd2; nchars = 3'd1; c0 = 6'd5; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd51; has_sh = 1'b1; mrow = 3'd0; mcol = 3'd4; is_shift = 1'b0; prow = 3'd0; end // 4
            6'd4: begin start = 5'd10; width = 5'd2; nchars = 3'd1; c0 = 6'd6; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd52; has_sh = 1'b1; mrow = 3'd0; mcol = 3'd5; is_shift = 1'b0; prow = 3'd0; end // 5
            6'd5: begin start = 5'd12; width = 5'd2; nchars = 3'd1; c0 = 6'd7; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd53; has_sh = 1'b1; mrow = 3'd0; mcol = 3'd6; is_shift = 1'b0; prow = 3'd0; end // 6
            6'd6: begin start = 5'd14; width = 5'd2; nchars = 3'd1; c0 = 6'd8; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd54; has_sh = 1'b1; mrow = 3'd0; mcol = 3'd7; is_shift = 1'b0; prow = 3'd0; end // 7
            6'd7: begin start = 5'd16; width = 5'd2; nchars = 3'd1; c0 = 6'd9; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd55; has_sh = 1'b1; mrow = 3'd1; mcol = 3'd0; is_shift = 1'b0; prow = 3'd0; end // 8
            6'd8: begin start = 5'd18; width = 5'd2; nchars = 3'd1; c0 = 6'd10; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd56; has_sh = 1'b1; mrow = 3'd1; mcol = 3'd1; is_shift = 1'b0; prow = 3'd0; end // 9
            6'd9: begin start = 5'd20; width = 5'd2; nchars = 3'd1; c0 = 6'd1; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd0; mcol = 3'd0; is_shift = 1'b0; prow = 3'd0; end // 0
            6'd10: begin start = 5'd22; width = 5'd2; nchars = 3'd1; c0 = 6'd37; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd57; has_sh = 1'b1; mrow = 3'd1; mcol = 3'd2; is_shift = 1'b0; prow = 3'd0; end // :
            6'd11: begin start = 5'd24; width = 5'd2; nchars = 3'd1; c0 = 6'd38; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd58; has_sh = 1'b1; mrow = 3'd1; mcol = 3'd5; is_shift = 1'b0; prow = 3'd0; end // -
            6'd12: begin start = 5'd26; width = 5'd4; nchars = 3'd3; c0 = 6'd12; c1 = 6'd28; c2 = 6'd21; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd6; mcol = 3'd2; is_shift = 1'b0; prow = 3'd0; end // BRK
            6'd13: begin start = 5'd2; width = 5'd2; nchars = 3'd1; c0 = 6'd44; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd5; mcol = 3'd3; is_shift = 1'b0; prow = 3'd1; end // UP
            6'd14: begin start = 5'd4; width = 5'd2; nchars = 3'd1; c0 = 6'd27; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd4; mcol = 3'd1; is_shift = 1'b0; prow = 3'd1; end // Q
            6'd15: begin start = 5'd6; width = 5'd2; nchars = 3'd1; c0 = 6'd33; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd4; mcol = 3'd7; is_shift = 1'b0; prow = 3'd1; end // W
            6'd16: begin start = 5'd8; width = 5'd2; nchars = 3'd1; c0 = 6'd15; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd2; mcol = 3'd5; is_shift = 1'b0; prow = 3'd1; end // E
            6'd17: begin start = 5'd10; width = 5'd2; nchars = 3'd1; c0 = 6'd28; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd4; mcol = 3'd2; is_shift = 1'b0; prow = 3'd1; end // R
            6'd18: begin start = 5'd12; width = 5'd2; nchars = 3'd1; c0 = 6'd30; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd4; mcol = 3'd4; is_shift = 1'b0; prow = 3'd1; end // T
            6'd19: begin start = 5'd14; width = 5'd2; nchars = 3'd1; c0 = 6'd35; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd5; mcol = 3'd1; is_shift = 1'b0; prow = 3'd1; end // Y
            6'd20: begin start = 5'd16; width = 5'd2; nchars = 3'd1; c0 = 6'd31; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd4; mcol = 3'd5; is_shift = 1'b0; prow = 3'd1; end // U
            6'd21: begin start = 5'd18; width = 5'd2; nchars = 3'd1; c0 = 6'd19; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd3; mcol = 3'd1; is_shift = 1'b0; prow = 3'd1; end // I
            6'd22: begin start = 5'd20; width = 5'd2; nchars = 3'd1; c0 = 6'd25; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd3; mcol = 3'd7; is_shift = 1'b0; prow = 3'd1; end // O
            6'd23: begin start = 5'd22; width = 5'd2; nchars = 3'd1; c0 = 6'd26; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd4; mcol = 3'd0; is_shift = 1'b0; prow = 3'd1; end // P
            6'd24: begin start = 5'd24; width = 5'd2; nchars = 3'd1; c0 = 6'd39; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd2; mcol = 3'd0; is_shift = 1'b0; prow = 3'd1; end // @
            6'd25: begin start = 5'd26; width = 5'd2; nchars = 3'd1; c0 = 6'd46; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd5; mcol = 3'd5; is_shift = 1'b0; prow = 3'd1; end // LT
            6'd26: begin start = 5'd28; width = 5'd2; nchars = 3'd1; c0 = 6'd47; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd5; mcol = 3'd6; is_shift = 1'b0; prow = 3'd1; end // RT
            6'd27: begin start = 5'd1; width = 5'd2; nchars = 3'd1; c0 = 6'd45; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd5; mcol = 3'd4; is_shift = 1'b0; prow = 3'd2; end // DN
            6'd28: begin start = 5'd3; width = 5'd2; nchars = 3'd1; c0 = 6'd11; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd2; mcol = 3'd1; is_shift = 1'b0; prow = 3'd2; end // A
            6'd29: begin start = 5'd5; width = 5'd2; nchars = 3'd1; c0 = 6'd29; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd4; mcol = 3'd3; is_shift = 1'b0; prow = 3'd2; end // S
            6'd30: begin start = 5'd7; width = 5'd2; nchars = 3'd1; c0 = 6'd14; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd2; mcol = 3'd4; is_shift = 1'b0; prow = 3'd2; end // D
            6'd31: begin start = 5'd9; width = 5'd2; nchars = 3'd1; c0 = 6'd16; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd2; mcol = 3'd6; is_shift = 1'b0; prow = 3'd2; end // F
            6'd32: begin start = 5'd11; width = 5'd2; nchars = 3'd1; c0 = 6'd17; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd2; mcol = 3'd7; is_shift = 1'b0; prow = 3'd2; end // G
            6'd33: begin start = 5'd13; width = 5'd2; nchars = 3'd1; c0 = 6'd18; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd3; mcol = 3'd0; is_shift = 1'b0; prow = 3'd2; end // H
            6'd34: begin start = 5'd15; width = 5'd2; nchars = 3'd1; c0 = 6'd20; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd3; mcol = 3'd2; is_shift = 1'b0; prow = 3'd2; end // J
            6'd35: begin start = 5'd17; width = 5'd2; nchars = 3'd1; c0 = 6'd21; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd3; mcol = 3'd3; is_shift = 1'b0; prow = 3'd2; end // K
            6'd36: begin start = 5'd19; width = 5'd2; nchars = 3'd1; c0 = 6'd22; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd3; mcol = 3'd4; is_shift = 1'b0; prow = 3'd2; end // L
            6'd37: begin start = 5'd21; width = 5'd2; nchars = 3'd1; c0 = 6'd40; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd59; has_sh = 1'b1; mrow = 3'd1; mcol = 3'd3; is_shift = 1'b0; prow = 3'd2; end // ;
            6'd38: begin start = 5'd23; width = 5'd4; nchars = 3'd3; c0 = 6'd15; c1 = 6'd24; c2 = 6'd30; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd6; mcol = 3'd0; is_shift = 1'b0; prow = 3'd2; end // ENT
            6'd39: begin start = 5'd27; width = 5'd4; nchars = 3'd3; c0 = 6'd13; c1 = 6'd22; c2 = 6'd28; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd6; mcol = 3'd1; is_shift = 1'b0; prow = 3'd2; end // CLR
            6'd40: begin start = 5'd2; width = 5'd4; nchars = 3'd3; c0 = 6'd29; c1 = 6'd18; c2 = 6'd16; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd6; mcol = 3'd7; is_shift = 1'b1; prow = 3'd3; end // SHF
            6'd41: begin start = 5'd6; width = 5'd2; nchars = 3'd1; c0 = 6'd36; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd5; mcol = 3'd2; is_shift = 1'b0; prow = 3'd3; end // Z
            6'd42: begin start = 5'd8; width = 5'd2; nchars = 3'd1; c0 = 6'd34; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd5; mcol = 3'd0; is_shift = 1'b0; prow = 3'd3; end // X
            6'd43: begin start = 5'd10; width = 5'd2; nchars = 3'd1; c0 = 6'd13; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd2; mcol = 3'd3; is_shift = 1'b0; prow = 3'd3; end // C
            6'd44: begin start = 5'd12; width = 5'd2; nchars = 3'd1; c0 = 6'd32; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd4; mcol = 3'd6; is_shift = 1'b0; prow = 3'd3; end // V
            6'd45: begin start = 5'd14; width = 5'd2; nchars = 3'd1; c0 = 6'd12; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd2; mcol = 3'd2; is_shift = 1'b0; prow = 3'd3; end // B
            6'd46: begin start = 5'd16; width = 5'd2; nchars = 3'd1; c0 = 6'd24; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd3; mcol = 3'd6; is_shift = 1'b0; prow = 3'd3; end // N
            6'd47: begin start = 5'd18; width = 5'd2; nchars = 3'd1; c0 = 6'd23; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd3; mcol = 3'd5; is_shift = 1'b0; prow = 3'd3; end // M
            6'd48: begin start = 5'd20; width = 5'd2; nchars = 3'd1; c0 = 6'd41; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd60; has_sh = 1'b1; mrow = 3'd1; mcol = 3'd4; is_shift = 1'b0; prow = 3'd3; end // ,
            6'd49: begin start = 5'd22; width = 5'd2; nchars = 3'd1; c0 = 6'd42; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd61; has_sh = 1'b1; mrow = 3'd1; mcol = 3'd6; is_shift = 1'b0; prow = 3'd3; end // .
            6'd50: begin start = 5'd24; width = 5'd2; nchars = 3'd1; c0 = 6'd43; c1 = 6'd0; c2 = 6'd0; c3 = 6'd0; c4 = 6'd0; sh = 6'd62; has_sh = 1'b1; mrow = 3'd1; mcol = 3'd7; is_shift = 1'b0; prow = 3'd3; end // /
            6'd51: begin start = 5'd26; width = 5'd4; nchars = 3'd3; c0 = 6'd29; c1 = 6'd18; c2 = 6'd16; c3 = 6'd0; c4 = 6'd0; sh = 6'd0; has_sh = 1'b0; mrow = 3'd6; mcol = 3'd7; is_shift = 1'b1; prow = 3'd3; end // SHF
            6'd52: begin start = 5'd8; width = 5'd16; nchars = 3'd5; c0 = 6'd29; c1 = 6'd26; c2 = 6'd11; c3 = 6'd13; c4 = 6'd15; sh = 6'd0; has_sh = 1'b0; mrow = 3'd5; mcol = 3'd7; is_shift = 1'b0; prow = 3'd4; end // SPACE
            default: ;
        endcase
    end
endmodule

// Which key covers half-unit hu of panel row prow: {hit, id}.
module osd_key_map (
    input  wire [2:0] prow,
    input  wire [4:0] hu,
    output reg        hit,
    output reg  [5:0] id
);
    always_comb begin
        hit = 1'b0; id = 6'd0;
        case ({prow, hu})
            {3'd0, 5'd2}: begin hit = 1'b1; id = 6'd0; end
            {3'd0, 5'd3}: begin hit = 1'b1; id = 6'd0; end
            {3'd0, 5'd4}: begin hit = 1'b1; id = 6'd1; end
            {3'd0, 5'd5}: begin hit = 1'b1; id = 6'd1; end
            {3'd0, 5'd6}: begin hit = 1'b1; id = 6'd2; end
            {3'd0, 5'd7}: begin hit = 1'b1; id = 6'd2; end
            {3'd0, 5'd8}: begin hit = 1'b1; id = 6'd3; end
            {3'd0, 5'd9}: begin hit = 1'b1; id = 6'd3; end
            {3'd0, 5'd10}: begin hit = 1'b1; id = 6'd4; end
            {3'd0, 5'd11}: begin hit = 1'b1; id = 6'd4; end
            {3'd0, 5'd12}: begin hit = 1'b1; id = 6'd5; end
            {3'd0, 5'd13}: begin hit = 1'b1; id = 6'd5; end
            {3'd0, 5'd14}: begin hit = 1'b1; id = 6'd6; end
            {3'd0, 5'd15}: begin hit = 1'b1; id = 6'd6; end
            {3'd0, 5'd16}: begin hit = 1'b1; id = 6'd7; end
            {3'd0, 5'd17}: begin hit = 1'b1; id = 6'd7; end
            {3'd0, 5'd18}: begin hit = 1'b1; id = 6'd8; end
            {3'd0, 5'd19}: begin hit = 1'b1; id = 6'd8; end
            {3'd0, 5'd20}: begin hit = 1'b1; id = 6'd9; end
            {3'd0, 5'd21}: begin hit = 1'b1; id = 6'd9; end
            {3'd0, 5'd22}: begin hit = 1'b1; id = 6'd10; end
            {3'd0, 5'd23}: begin hit = 1'b1; id = 6'd10; end
            {3'd0, 5'd24}: begin hit = 1'b1; id = 6'd11; end
            {3'd0, 5'd25}: begin hit = 1'b1; id = 6'd11; end
            {3'd0, 5'd26}: begin hit = 1'b1; id = 6'd12; end
            {3'd0, 5'd27}: begin hit = 1'b1; id = 6'd12; end
            {3'd0, 5'd28}: begin hit = 1'b1; id = 6'd12; end
            {3'd0, 5'd29}: begin hit = 1'b1; id = 6'd12; end
            {3'd1, 5'd2}: begin hit = 1'b1; id = 6'd13; end
            {3'd1, 5'd3}: begin hit = 1'b1; id = 6'd13; end
            {3'd1, 5'd4}: begin hit = 1'b1; id = 6'd14; end
            {3'd1, 5'd5}: begin hit = 1'b1; id = 6'd14; end
            {3'd1, 5'd6}: begin hit = 1'b1; id = 6'd15; end
            {3'd1, 5'd7}: begin hit = 1'b1; id = 6'd15; end
            {3'd1, 5'd8}: begin hit = 1'b1; id = 6'd16; end
            {3'd1, 5'd9}: begin hit = 1'b1; id = 6'd16; end
            {3'd1, 5'd10}: begin hit = 1'b1; id = 6'd17; end
            {3'd1, 5'd11}: begin hit = 1'b1; id = 6'd17; end
            {3'd1, 5'd12}: begin hit = 1'b1; id = 6'd18; end
            {3'd1, 5'd13}: begin hit = 1'b1; id = 6'd18; end
            {3'd1, 5'd14}: begin hit = 1'b1; id = 6'd19; end
            {3'd1, 5'd15}: begin hit = 1'b1; id = 6'd19; end
            {3'd1, 5'd16}: begin hit = 1'b1; id = 6'd20; end
            {3'd1, 5'd17}: begin hit = 1'b1; id = 6'd20; end
            {3'd1, 5'd18}: begin hit = 1'b1; id = 6'd21; end
            {3'd1, 5'd19}: begin hit = 1'b1; id = 6'd21; end
            {3'd1, 5'd20}: begin hit = 1'b1; id = 6'd22; end
            {3'd1, 5'd21}: begin hit = 1'b1; id = 6'd22; end
            {3'd1, 5'd22}: begin hit = 1'b1; id = 6'd23; end
            {3'd1, 5'd23}: begin hit = 1'b1; id = 6'd23; end
            {3'd1, 5'd24}: begin hit = 1'b1; id = 6'd24; end
            {3'd1, 5'd25}: begin hit = 1'b1; id = 6'd24; end
            {3'd1, 5'd26}: begin hit = 1'b1; id = 6'd25; end
            {3'd1, 5'd27}: begin hit = 1'b1; id = 6'd25; end
            {3'd1, 5'd28}: begin hit = 1'b1; id = 6'd26; end
            {3'd1, 5'd29}: begin hit = 1'b1; id = 6'd26; end
            {3'd2, 5'd1}: begin hit = 1'b1; id = 6'd27; end
            {3'd2, 5'd2}: begin hit = 1'b1; id = 6'd27; end
            {3'd2, 5'd3}: begin hit = 1'b1; id = 6'd28; end
            {3'd2, 5'd4}: begin hit = 1'b1; id = 6'd28; end
            {3'd2, 5'd5}: begin hit = 1'b1; id = 6'd29; end
            {3'd2, 5'd6}: begin hit = 1'b1; id = 6'd29; end
            {3'd2, 5'd7}: begin hit = 1'b1; id = 6'd30; end
            {3'd2, 5'd8}: begin hit = 1'b1; id = 6'd30; end
            {3'd2, 5'd9}: begin hit = 1'b1; id = 6'd31; end
            {3'd2, 5'd10}: begin hit = 1'b1; id = 6'd31; end
            {3'd2, 5'd11}: begin hit = 1'b1; id = 6'd32; end
            {3'd2, 5'd12}: begin hit = 1'b1; id = 6'd32; end
            {3'd2, 5'd13}: begin hit = 1'b1; id = 6'd33; end
            {3'd2, 5'd14}: begin hit = 1'b1; id = 6'd33; end
            {3'd2, 5'd15}: begin hit = 1'b1; id = 6'd34; end
            {3'd2, 5'd16}: begin hit = 1'b1; id = 6'd34; end
            {3'd2, 5'd17}: begin hit = 1'b1; id = 6'd35; end
            {3'd2, 5'd18}: begin hit = 1'b1; id = 6'd35; end
            {3'd2, 5'd19}: begin hit = 1'b1; id = 6'd36; end
            {3'd2, 5'd20}: begin hit = 1'b1; id = 6'd36; end
            {3'd2, 5'd21}: begin hit = 1'b1; id = 6'd37; end
            {3'd2, 5'd22}: begin hit = 1'b1; id = 6'd37; end
            {3'd2, 5'd23}: begin hit = 1'b1; id = 6'd38; end
            {3'd2, 5'd24}: begin hit = 1'b1; id = 6'd38; end
            {3'd2, 5'd25}: begin hit = 1'b1; id = 6'd38; end
            {3'd2, 5'd26}: begin hit = 1'b1; id = 6'd38; end
            {3'd2, 5'd27}: begin hit = 1'b1; id = 6'd39; end
            {3'd2, 5'd28}: begin hit = 1'b1; id = 6'd39; end
            {3'd2, 5'd29}: begin hit = 1'b1; id = 6'd39; end
            {3'd2, 5'd30}: begin hit = 1'b1; id = 6'd39; end
            {3'd3, 5'd2}: begin hit = 1'b1; id = 6'd40; end
            {3'd3, 5'd3}: begin hit = 1'b1; id = 6'd40; end
            {3'd3, 5'd4}: begin hit = 1'b1; id = 6'd40; end
            {3'd3, 5'd5}: begin hit = 1'b1; id = 6'd40; end
            {3'd3, 5'd6}: begin hit = 1'b1; id = 6'd41; end
            {3'd3, 5'd7}: begin hit = 1'b1; id = 6'd41; end
            {3'd3, 5'd8}: begin hit = 1'b1; id = 6'd42; end
            {3'd3, 5'd9}: begin hit = 1'b1; id = 6'd42; end
            {3'd3, 5'd10}: begin hit = 1'b1; id = 6'd43; end
            {3'd3, 5'd11}: begin hit = 1'b1; id = 6'd43; end
            {3'd3, 5'd12}: begin hit = 1'b1; id = 6'd44; end
            {3'd3, 5'd13}: begin hit = 1'b1; id = 6'd44; end
            {3'd3, 5'd14}: begin hit = 1'b1; id = 6'd45; end
            {3'd3, 5'd15}: begin hit = 1'b1; id = 6'd45; end
            {3'd3, 5'd16}: begin hit = 1'b1; id = 6'd46; end
            {3'd3, 5'd17}: begin hit = 1'b1; id = 6'd46; end
            {3'd3, 5'd18}: begin hit = 1'b1; id = 6'd47; end
            {3'd3, 5'd19}: begin hit = 1'b1; id = 6'd47; end
            {3'd3, 5'd20}: begin hit = 1'b1; id = 6'd48; end
            {3'd3, 5'd21}: begin hit = 1'b1; id = 6'd48; end
            {3'd3, 5'd22}: begin hit = 1'b1; id = 6'd49; end
            {3'd3, 5'd23}: begin hit = 1'b1; id = 6'd49; end
            {3'd3, 5'd24}: begin hit = 1'b1; id = 6'd50; end
            {3'd3, 5'd25}: begin hit = 1'b1; id = 6'd50; end
            {3'd3, 5'd26}: begin hit = 1'b1; id = 6'd51; end
            {3'd3, 5'd27}: begin hit = 1'b1; id = 6'd51; end
            {3'd3, 5'd28}: begin hit = 1'b1; id = 6'd51; end
            {3'd3, 5'd29}: begin hit = 1'b1; id = 6'd51; end
            {3'd4, 5'd8}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd9}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd10}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd11}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd12}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd13}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd14}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd15}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd16}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd17}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd18}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd19}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd20}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd21}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd22}: begin hit = 1'b1; id = 6'd52; end
            {3'd4, 5'd23}: begin hit = 1'b1; id = 6'd52; end
            default: ;
        endcase
    end
endmodule

// First key id and key count of each panel row.
module osd_row_info (
    input  wire [2:0] prow,
    output reg  [5:0] first,
    output reg  [5:0] count
);
    always_comb begin
        case (prow)
            3'd0: begin first = 6'd0; count = 6'd13; end
            3'd1: begin first = 6'd13; count = 6'd14; end
            3'd2: begin first = 6'd27; count = 6'd13; end
            3'd3: begin first = 6'd40; count = 6'd12; end
            3'd4: begin first = 6'd52; count = 6'd1; end
            default: begin first = 6'd0; count = 6'd1; end
        endcase
    end
endmodule

`default_nettype wire
