//
// On-screen keyboard for undocked use (no USB keyboard).
//
// Select opens/closes a 256x62 panel showing the Dragon's own keyboard
// layout, drawn into the frame buffer through video_frame_buffer.sv's
// wr_overlay_en/wr_overlay_color ports (no second buffer: M10K is
// 308/308). While open:
//   d-pad  - move the highlight (repeats when held: 20 frames, then 5)
//   A      - press the highlighted key; it stays down while A is held
//            (at least MIN_HOLD frames, so a quick tap still registers)
//   B      - latch Shift for the next key (also: A on either SHF key).
//            Released after that key; keys show their shifted symbol
//            while it's latched
//   X      - move the panel between the bottom and top of the screen
// The d-pad and A are taken off the Dragon joystick while the panel is
// open (core_top.v masks them with `active`).
//
// The pressed key comes out as a Dragon matrix position (key_row/key_col)
// plus key_shift, which dragon_keyboard.sv ORs into the matrix alongside
// the USB keyboard.
//
// Drawing: px_x/px_y are the frame buffer's write position - the pixel
// it will write next. The Dragon writes a pixel every 8 clk cycles, so
// the 4-stage pipeline below has its colour ready well before the write.
// Font, key table and position map are combinational logic generated by
// tools/gen_osd_tables.py (osd_keyboard_tables.sv).
//
// Colours are primary/neutral only (black panel, blue keys, white text,
// yellow highlight with black text, green latched SHIFT).
//
`default_nettype none

module osd_keyboard (
    input  wire        clk,
    input  wire [15:0] btn,        // cont1_key[15:0], synchronised to clk
    input  wire        vsync,      // Dragon vsync - one frame tick per rising edge

    input  wire [7:0]  px_x,       // next pixel the frame buffer writes
    input  wire [7:0]  px_y,
    output reg         ov_en = 1'b0,
    output reg  [23:0] ov_color = 24'h000000,

    output wire        active,     // panel open - mask d-pad/A from the joystick
    output reg         key_valid = 1'b0,
    output reg  [2:0]  key_row = 3'd0,
    output reg  [2:0]  key_col = 3'd0,
    output wire        key_shift
);

    // Pocket controller bits (cont1_key)
    localparam B_UP = 0, B_DOWN = 1, B_LEFT = 2, B_RIGHT = 3,
               B_A = 4, B_B = 5, B_X = 6, B_SELECT = 14;

    localparam PANEL_H  = 62;      // 1 px margin + 5 rows x 12 + 1 px margin
    localparam Y_BOTTOM = 192 - PANEL_H;
    localparam MIN_HOLD = 3;       // frames
    localparam REPEAT_FIRST = 20, REPEAT_NEXT = 5;   // frames

    localparam [23:0] C_PANEL = 24'h000000, C_KEY = 24'h0000C0,
                      C_SEL = 24'hFFFF00, C_SHIFT = 24'h00C000,
                      C_TEXT = 24'hFFFFFF, C_SEL_TEXT = 24'h000000;

    reg        open = 1'b0;
    reg        at_top = 1'b0;
    reg        shift_latched = 1'b0;
    reg  [5:0] cursor = 6'd0;      // key id, see osd_keyboard_tables.sv

    assign active    = open;
    assign key_shift = open & shift_latched;

    // ------------------------------------------------------------------
    // Controls
    // ------------------------------------------------------------------
    reg [15:0] btn_prev = 16'd0;
    reg        vsync_prev = 1'b0;
    wire       frame_tick = vsync & ~vsync_prev;
    wire [15:0] pressed_now = btn & ~btn_prev;

    // cursor key's attributes
    wire [4:0] cur_start, cur_width;
    wire [2:0] cur_mrow, cur_mcol, cur_prow;
    wire       cur_is_shift;
    osd_key_table cur_tab (
        .id(cursor), .start(cur_start), .width(cur_width), .nchars(),
        .c0(), .c1(), .c2(), .c3(), .c4(), .sh(), .has_sh(),
        .mrow(cur_mrow), .mcol(cur_mcol), .is_shift(cur_is_shift), .prow(cur_prow)
    );
    wire [5:0] cur_first, cur_count;
    osd_row_info cur_row_info (.prow(cur_prow), .first(cur_first), .count(cur_count));

    // vertical moves take two cycles: pick the row and the cursor key's
    // centre, then find the key under that centre on the new row
    reg        vmove = 1'b0;
    reg  [2:0] v_row = 3'd0;
    reg  [4:0] v_hu = 5'd0;
    wire       v_hit;
    wire [5:0] v_id, v_first, v_count;
    osd_key_map    v_map  (.prow(v_row), .hu(v_hu), .hit(v_hit), .id(v_id));
    osd_row_info   v_info (.prow(v_row), .first(v_first), .count(v_count));

    // d-pad repeat
    wire [3:0] dpad = btn[3:0];
    reg  [3:0] dpad_prev = 4'd0;
    reg  [4:0] rep_cnt = 5'd0;
    reg        do_move;

    always_comb begin
        do_move = 1'b0;
        if (dpad != 4'd0) begin
            if (dpad != dpad_prev)                  do_move = 1'b1;
            else if (frame_tick && rep_cnt == 5'd0) do_move = 1'b1;
        end
    end

    // key press
    reg        a_key = 1'b0;       // A is holding a matrix key down
    reg  [1:0] hold_cnt = 2'd0;

    always @(posedge clk) begin
        btn_prev   <= btn;
        vsync_prev <= vsync;
        dpad_prev  <= dpad;
        vmove      <= 1'b0;

        if (pressed_now[B_SELECT]) open <= ~open;

        if (!open) begin
            shift_latched <= 1'b0;
            a_key         <= 1'b0;
            key_valid     <= 1'b0;
            hold_cnt      <= 2'd0;
        end else begin
            if (pressed_now[B_X]) at_top <= ~at_top;
            if (pressed_now[B_B]) shift_latched <= ~shift_latched;

            // d-pad
            if (do_move)
                // the next move fires on the tick after rep_cnt reaches 0, hence -1
                rep_cnt <= (dpad != dpad_prev) ? REPEAT_FIRST[4:0] - 5'd1 : REPEAT_NEXT[4:0] - 5'd1;
            else if (frame_tick && rep_cnt != 5'd0)
                rep_cnt <= rep_cnt - 5'd1;

            if (do_move && !a_key) begin
                if (dpad[B_LEFT])
                    cursor <= (cursor == cur_first) ? cur_first + cur_count - 6'd1 : cursor - 6'd1;
                else if (dpad[B_RIGHT])
                    cursor <= (cursor == cur_first + cur_count - 6'd1) ? cur_first : cursor + 6'd1;
                else begin
                    v_row <= dpad[B_UP] ? ((cur_prow == 3'd0) ? 3'd4 : cur_prow - 3'd1)
                                        : ((cur_prow == 3'd4) ? 3'd0 : cur_prow + 3'd1);
                    v_hu  <= cur_start + {1'b0, cur_width[4:1]};
                    vmove <= 1'b1;
                end
            end
            if (vmove)
                cursor <= v_hit ? v_id : (v_hu < 5'd16) ? v_first : v_first + v_count - 6'd1;

            // A
            if (pressed_now[B_A]) begin
                if (cur_is_shift) begin
                    shift_latched <= ~shift_latched;
                end else begin
                    a_key     <= 1'b1;
                    key_valid <= 1'b1;
                    key_row   <= cur_mrow;
                    key_col   <= cur_mcol;
                    hold_cnt  <= MIN_HOLD[1:0];
                end
            end else if (a_key) begin
                if (frame_tick && hold_cnt != 2'd0)
                    hold_cnt <= hold_cnt - 2'd1;
                if (!btn[B_A] && hold_cnt == 2'd0) begin
                    a_key         <= 1'b0;
                    key_valid     <= 1'b0;
                    shift_latched <= 1'b0;   // one-shot: released after the key
                end
            end
        end
    end

    // ------------------------------------------------------------------
    // Drawing pipeline
    // ------------------------------------------------------------------
    // stage 1: panel row and line within it
    wire [7:0] y0 = at_top ? 8'd0 : Y_BOTTOM[7:0];
    wire [7:0] py = px_y - y0 - 8'd1;            // 0 = first key line
    reg        s1_in = 1'b0;
    reg  [2:0] s1_prow = 3'd0;
    reg  [3:0] s1_ry = 4'd0;
    reg  [7:0] s1_x = 8'd0;
    always @(posedge clk) begin
        s1_in <= open && px_y >= y0 && px_y < y0 + PANEL_H;
        s1_x  <= px_x;
        if      (py < 8'd12) begin s1_prow <= 3'd0; s1_ry <= py[3:0];           end
        else if (py < 8'd24) begin s1_prow <= 3'd1; s1_ry <= py[3:0] - 4'd12;   end
        else if (py < 8'd36) begin s1_prow <= 3'd2; s1_ry <= py[3:0] - 4'd8;    end // (py-24) mod 16
        else if (py < 8'd48) begin s1_prow <= 3'd3; s1_ry <= py[3:0] - 4'd4;    end // (py-36)
        else if (py < 8'd60) begin s1_prow <= 3'd4; s1_ry <= py[3:0] - 4'd0;    end // (py-48)
        else                 begin s1_prow <= 3'd7; s1_ry <= 4'd15;             end // margin
    end

    // stage 2: which key
    wire       m_hit;
    wire [5:0] m_id;
    osd_key_map px_map (.prow(s1_prow), .hu(s1_x[7:3]), .hit(m_hit), .id(m_id));
    reg        s2_in = 1'b0, s2_hit = 1'b0;
    reg  [5:0] s2_id = 6'd0;
    reg  [3:0] s2_ry = 4'd0;
    reg  [7:0] s2_x = 8'd0;
    always @(posedge clk) begin
        s2_in  <= s1_in;
        s2_hit <= m_hit;
        s2_id  <= m_id;
        s2_ry  <= s1_ry;
        s2_x   <= s1_x;
    end

    // stage 3: inside the key box? which label character and glyph pixel?
    wire [4:0] t_start, t_width;
    wire [2:0] t_nchars;
    wire [5:0] t_c0, t_c1, t_c2, t_c3, t_c4, t_sh;
    wire       t_has_sh, t_is_shift;
    osd_key_table px_tab (
        .id(s2_id), .start(t_start), .width(t_width), .nchars(t_nchars),
        .c0(t_c0), .c1(t_c1), .c2(t_c2), .c3(t_c3), .c4(t_c4), .sh(t_sh), .has_sh(t_has_sh),
        .mrow(), .mcol(), .is_shift(t_is_shift), .prow()
    );
    wire       use_sh = shift_latched && t_has_sh;
    wire [2:0] n      = use_sh ? 3'd1 : t_nchars;
    wire [7:0] kx     = s2_x - {t_start, 3'b000};
    wire [7:0] kw     = {t_width, 3'b000};
    wire [7:0] lstart = {1'b0, t_width - {2'b00, n}, 2'b00};     // (width - n) * 8 / 2
    wire [7:0] lx     = kx - lstart;
    reg  [5:0] ch;
    always_comb begin
        if (use_sh) ch = t_sh;
        else case (lx[5:3])
            3'd0: ch = t_c0;
            3'd1: ch = t_c1;
            3'd2: ch = t_c2;
            3'd3: ch = t_c3;
            default: ch = t_c4;
        endcase
    end

    reg        s3_in = 1'b0, s3_box = 1'b0, s3_glyph = 1'b0, s3_sel = 1'b0, s3_shiftkey = 1'b0;
    reg  [5:0] s3_ch = 6'd0;
    reg  [2:0] s3_grow = 3'd0, s3_gcol = 3'd0;
    always @(posedge clk) begin
        s3_in       <= s2_in;
        s3_box      <= s2_hit && kx < kw - 8'd1 && s2_ry < 4'd11;
        s3_glyph    <= s2_hit && lx < {2'b00, n, 3'b000} && s2_ry >= 4'd2 && s2_ry < 4'd9;
        s3_sel      <= s2_id == cursor;
        s3_shiftkey <= t_is_shift;
        s3_ch       <= ch;
        s3_grow     <= s2_ry[2:0] - 3'd2;
        s3_gcol     <= lx[2:0];
    end

    // stage 4: font lookup and colour
    wire [4:0] bits;
    osd_font_rom font (.ch(s3_ch), .row(s3_grow), .bits(bits));
    wire lit = s3_glyph && s3_gcol >= 3'd1 && s3_gcol <= 3'd5 && bits[3'd5 - s3_gcol];

    always @(posedge clk) begin
        ov_en <= s3_in;
        if (!s3_box)
            ov_color <= C_PANEL;
        else if (lit)
            ov_color <= s3_sel ? C_SEL_TEXT : C_TEXT;
        else if (s3_sel)
            ov_color <= C_SEL;
        else if (s3_shiftkey && shift_latched)
            ov_color <= C_SHIFT;
        else
            ov_color <= C_KEY;
    end

endmodule

`default_nettype wire
